import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Providers from "./Providers";

const almarai = localFont({
  src: [
    {
      path: "./fonts/Almarai-Light.ttf",
      weight: "300",
    },
    {
      path: "./fonts/Almarai-Regular.ttf",
      weight: "400"
    },
    {
      path: "./fonts/Almarai-Bold.ttf",
      weight: "700"
    }
  ],
  variable: "--font-almarai",
  display: "swap"
});

const vip = localFont({
  src: "./fonts/VIP-Hala-Bold-2.otf",
  variable: "--font-vip",
  display: "swap"
});


export const metadata = {
  title: "Omar Mamdouh",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={`${almarai.variable} ${vip.variable} antialiased`}
      >
        <Providers>
            <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
